steps:
  - command: scripts/check-version.sh
    label: ":point_up:"

  - wait

  - command: scripts/build-image.sh
    label: ":hammer: :docker:"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: builder

  - wait

  # - command: scripts/deploy-github.sh
  #   label: ":rocket: :github:"
  #   env:
  #     BUILDKITE_DOCKER_COMPOSE_CONTAINER: builder
  #   branches: master

  - command: scripts/deploy-dockerhub.sh
    label: ":rocket: :docker:"
    branches: master

  - wait

  - command: scripts/deploy-cluster.sh
    label: ":rocket: :node:"
    agents:
      - queue=deploy
      - cluster=polltal
      - env=test
    branches: master
