steps:
  - command: scripts/build-image.sh
    label: ":hammer: :docker:"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: polltal-app

  # - command: scripts/test-unit.sh
  #   label: ":eslint: :new_moon_with_face: :partyparrot:"
  #   env:
  #     BUILDKITE_DOCKER_COMPOSE_CONTAINER: polltal-api

  # - command: scripts/test-integration.sh
  #   label: ":llama:"
  #   env:
  #     BUILDKITE_DOCKER_COMPOSE_CONTAINER: polltal-api-test

  - command: scripts/check-version.sh
    label: ":point_up:"

  - wait

  - command: scripts/deploy-github.sh
    label: ":rocket: :github:"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: polltal-app-test
    branches: master

  - command: scripts/deploy-dockerhub.sh
    label: ":rocket: :docker:"
    branches: master
