steps:
  - command: scripts/build-image.sh
    label: ":hammer: :docker:"
    env:
      BUILDKITE_DOCKER_COMPOSE_CONTAINER: polltal-app

  - command: scripts/check-version.sh
    label: ":point_up:"

  - wait

  - command: scripts/deploy-github.sh
    label: ":rocket: :github:"
    branches: master

  - command: scripts/deploy-dockerhub.sh
    label: ":rocket: :docker:"
    branches: master
